### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by Pogogo007** [CachyOS/CachyOS-Handheld#9]
- [x] Switch SDDM to Wayland [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/8b1bbd778f4ede53e92689fa6a6dccfd2458b3c5) 
- [x] Add steam autostart [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/8c25d2f809f971a1e50e640aaad2bcbc08ba6ded)
- [x] add environment variable for HHD to reduce QAM latency [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/d0d3a3ee5f1c908010b64d00c052a4ee9558583f)
- [x] Add KDE Customizations [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/bd43e202b127f3175dfbdd69219bee3d1fc2afa3)
- [x] Add kernel argument to help switching. [Relevant PR](https://github.com/CachyOS/cachyos-calamares/pull/21)
- [x] Add DECKY_USER_HOME env variable to allow decky plugins to use correct home path (Thanks souly) [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/ca592ad86211404277d4ba266522a7363463d1d8)
- [x] Allow any username to be used [Calamares PR](https://github.com/CachyOS/cachyos-calamares/pull/22) [.install PR](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/207)
- [x] Enable services for appropriate devices (CHWD) [PR](https://github.com/CachyOS/chwd/pull/100)
- [x] Add Kernel arguments specific to certain devices. (CHWD) [PR](https://github.com/CachyOS/chwd/pull/100)
- [x] Maliit dark mode
- [x] Switch to use valve powerbuttond and hdd [Relevant PR](https://github.com/CachyOS/chwd/pull/101) [Patch](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/213) [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/5f6b03dcb66d188d16c9800b8bfd13cc5efdd46c)
- [x] Add regex matching for chwd [PR](https://github.com/CachyOS/chwd/pull/102)
- [x] Add Vapor/Look-And-Feel [Repo](https://github.com/CachyOS/cachyos-vapor)
- [x] Make add to steam shortcut work on windows exe's [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/c2919ecd19c2e19c43ea4b159adcd077fa088358)
- [x] Add customizable scaling options for deckscale [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/49c450481771533e18a9f7fa2bc696662b908293)
- [x] Fix HHD_QAM_GAMESCOPE=1 [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/2c1a1c3960ef685623773a1da1f7febbdb65a79a)
- [x] Switch to LAVD being off by default until performance issues are fixed
- [x] Implement auto mount for gamemode [PR](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/231)
- [x] Allow steam to manage external storage devices [PR](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/236)
- [x] Allow sdboot-manage to source external kernel params [PR](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/237)
- [x] Fix process names for teardown workaround
- [x] Fix adaptive brightness on deck, fix hdr on OLED, possible fix for framerate limiter [PR](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/249)
- [x] Create sd-boot-manager scripts for kernel args for each device [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/e5f1ab286744cb135c4935c00f17b0b84e0d18f2)
- [x] Add amdgpu.sg_display=0 to legion go only [Commit](https://github.com/CachyOS/CachyOS-Handheld/commit/e5f1ab286744cb135c4935c00f17b0b84e0d18f2)
- [x] Add symlink to powerbuttond to use upstream gamescope-session [MR](https://github.com/CachyOS/CachyOS-PKGBUILDS/pull/298)
- [ ] add bluetooth as a dep so it gets installed before the enable runs
- [x] cleanup and per device chwd [PR](https://github.com/CachyOS/chwd/pull/115)
- [ ] pacnew for scaling config
- [x] Implement bios updater for jupiter/galileo
- [ ] Allow user to select x11 instead of wayland for desktop session
- [x] Create wrapper script for unlocking and relocking jupiter/galileo bios (Cancelled, script works on too few hardware/bios combinations)
- [x] Fix initial flashbang/add first boot bootstrap
- [ ] Force scaling option to appear by default
- [x] Add support for more devices. (Requires Testers. Please mention Nekoh in the #handheld-edition channel on the CachyOS discord)
- [x] Provide own gamescope (Custom Refresh Rate and co)
- [x] Update to the latest SteamDeck packages (fan-control, hw-support, firmware and co)

### Relevant projects
[Kernel used for handheld edition](https://github.com/CachyOS/linux-cachyos/tree/master/linux-cachyos-deckify)
[Handheld PKGBUILDS](https://github.com/CachyOS/CachyOS-PKGBUILDS/tree/master/deckify)
[Handheld calamares branch](https://github.com/CachyOS/cachyos-calamares/tree/cachyos-deckify-qt6)
[Handheld iso branch](https://github.com/CachyOS/CachyOS-Live-ISO/tree/cachyos-deckify)
[CHWD Profiles](https://github.com/CachyOS/chwd/blob/master/profiles/pci/handhelds/profiles.toml)
[Vapor Theme](https://github.com/CachyOS/cachyos-vapor)

**Comment by 1Naim** [comment]
Marking own gamescope and latest packages as solved:

gamescope:
 - we're relying on upstream now. it supports per display configuration scripts so if we ever want to add support for more devices than what is not already available, we can do so in this repo 
- we can still fork the upstream repo and cherrypick some OOT patches for more compatibility with handheld devices

latest steamdeck packages:
- i've updated all (except the steam bootstrap package in post install script) to latest. includes powerbuttond, jupiter-hw-support, steamdeck-dsp, etc
